### ISSUE TITLE
generating svg with the diagrams CLI

### ISSUE THREAD

**Issue by chiefbiiko** [francoislaberge/atom-diagrams#14]
got my .sequence ready - previewing it in atom
but cannot generate svg with the CLI - neither global nor local installation does it using
`diagrams watch --build .`

know what im doing wrong?

**Comment by seflless** [comment]
Mind sending me your folder structure with your .sequence files in it? You can strip out any extraneous files not relevant to reproducing the issue.

**Comment by seflless** [comment]
@chiefBiiko Also, can you open this issue on the diagrams repo instead of here?
https://github.com/francoislaberge/diagrams
