### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by ymiroshnyk** [francoislaberge/atom-diagrams#23]
I installed the plugin, created file .sequence, wrote a sample provided in documentation.
I see syntax highlighting, obviously is made by the plugin,
but I don't see any charts rendering in the Atom.
Is there something I missing of?

![image](https://user-images.githubusercontent.com/4577607/58322283-23bf2880-7e29-11e9-9127-05136f716853.png)

**Comment by Francois-Laberge-Bose** [comment]
That's not right. Try opening the developer tools and looking if there are any errors.

**Comment by Francois-Laberge-Bose** [comment]
Did you name it `.sequence`? Not sure it would support that, if so try `test.sequence`.

**Comment by ymiroshnyk** [comment]
Yep. test.sequence works well. Thanks.

Previously, I created empty document, wrote sample there and saved it as test.sequence. And it doesn't work like that.
But if to close Atom and reopen the file (test.sequence) it works correctly.

**Comment by Francois-Laberge-Bose** [comment]
Perfect
