### ISSUE TITLE
Deprecated selector in `diagrams/styles/diagrams.less`

### ISSUE THREAD

**Issue by xguse** [francoislaberge/atom-diagrams#6]
In `diagrams/styles/diagrams.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .gutter .line-number.diagrams-line-number-red` => `atom-text-editor.editor .gutter .line-number.diagrams-line-number-red`

* `atom-text-editor::shadow .diagrams-highlight-red .region` => `atom-text-editor.editor .diagrams-highlight-red .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by seflless** [comment]
Thanks for the heads up

Does this look right?
https://github.com/francoislaberge/atom-diagrams/commit/ac4adacc76b142ab2119c62241e3e686af91ee0a

I didn't follow the `and prepend all your syntax selectors with syntax--` part of what you were saying though.
